---

# source: https://lists.fedoraproject.org/pipermail/users/2014-July/452133.html
- blockinfile:
    dest: ~/.bashrc
    marker: '# {mark} ANSIBLE MANAGED BLOCK for man-user role'
    create: true
    block: |
      man() {
        LESS_TERMCAP_mb=$'\e[01;31m' \
        LESS_TERMCAP_md=$'\e[01;34m' \
        LESS_TERMCAP_me=$'\e[0m' \
        LESS_TERMCAP_se=$'\e[0m' \
        LESS_TERMCAP_so=$'\e[01;33;40m' \
        LESS_TERMCAP_ue=$'\e[0m' \
        LESS_TERMCAP_us=$'\e[01;04;35m' \
        GROFF_NO_SGR=yes \
        command man "$@"
      }
