- shell: cd {{ project_dir }}/drake && { ! git diff --quiet HEAD ;}
  register: drake_local
  changed_when: false
  failed_when: drake_local.rc > 1

- git: >
    repo=https://github.com/Factual/drake.git
    dest={{ project_dir }}/drake
  when: drake_local.rc != 0
  register: drake

- stat: path={{ project_dir }}/drake/target/drake.jar
  register: drake_target_jar

- command: bash -c 'lein uberjar' chdir={{ project_dir }}/drake
  when: drake_target_jar.stat.exists == false or drake.changed

- stat: path=~/bin/drake.jar
  register: drake_bin_jar

- copy: >
    src={{ project_dir }}/drake/target/drake.jar
    dest=~/bin/
  when: drake_bin_jar.stat.exists == false or drake.changed

- stat: path=~/bin/drake
  register: drake_bin

- copy:
    content: |
      echo #!/bin/bash
      java -cp $(dirname $0)/drake.jar drake.core "$@" 
    dest: ~/bin/drake
    mode: 0755
  when: drake_bin.stat.exists == false or drake.changed

- include: vim.yml
