- get_url: 
    url=https://repos.fedorapeople.org/repos/spot/chromium/fedora-chromium-stable.repo
    dest=/etc/yum.repos.d/

- get_url: 
    url=https://repos.fedorapeople.org/repos/spot/chromium/spot.gpg
    dest=/etc/pki/rpm-gpg/

- yum: name=chromium

- lineinfile:
    dest: /etc/xdg/mimeapps.list
    create: yes
    line: '[Default Applications]'

- lineinfile:
    dest: /etc/xdg/mimeapps.list
    create: yes
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: '{{ (set_default_browser | default(false)) | ternary("present", "absent") }}'
  with_items:
    - { regexp: '^text/html=', line: 'text/html=chromium-browser.desktop' }
    - { regexp: '^application/xhtml\+xml=', line: 'application/xhtml+xml=chromium-browser.desktop' }
    - { regexp: '^x-scheme-handler/http=', line: 'x-scheme-handler/http=chromium-browser.desktop' }
    - { regexp: '^x-scheme-handler/https=', line: 'x-scheme-handler/https=chromium-browser.desktop' }

- copy: src=master_preferences dest=/usr/lib64/chromium-browser/

