- package: name="@virtualisation" state=present
  become: true

# workaround https://bugzilla.redhat.com/show_bug.cgi?id=1105274
- file: >
    path=~/.config/libvirt/qemu/lib/channel/target
    state=directory
