---
- hosts: fedora-workstation 
  become: true
  gather_facts: false

  tasks:
    - name: install python 2 dependencies for ansible modules
      raw: dnf install -y python2 python2-dnf libselinux-python python-yumdaemon

- hosts: fedora-workstation
  become: true

  roles:
    - { role: fontconfig, serif: 'Liberation Serif', sans_serif: 'Liberation Sans', monospace: 'Liberation Mono' }
    - { role: gnome-fonts, hinting: 'slight', antialiasing: 'rgba', lcdfilter: 'lcddefault' }
    - gnome-extras
    - { role: chromium, set_default_browser: false }
    - chrome
    - gstreamer-plugins
    - libreoffice
    - atom
    - libva
    - bluray

