---

- hosts: fedora-workstation
  become: false

  vars:
    firefox:
      addons:
        - url: https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-2
        - url: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin
        - url: https://addons.mozilla.org/firefox/downloads/file/495444/lastpass_password_manager-4.1.29a-an+fx.xpi
      prefs:
        - name: mousewheel.default.delta_multiplier_y
          value: 200
        - name: signon.rememberSignons
          value: false

  roles:
    - alzadude.firefox
