---
- hosts: fedora-workstation
  sudo: no

  vars:
    - ssh_user:
        ssh_askpass: ''
        ssh_config_all_hosts:
          - keyword: NoHostAuthenticationForLocalhost
            arguments: 'yes'
          - keyword: ServerAliveInterval
            arguments: 60
    - markdown_user:
        vim_markdown_preview_browser: Firefox
        vim_markdown_preview_use_xdg_open: 1

  roles:
    - ssh-user
    - { role: vim-user, set_visual: true }
    - { role: git-user, config_credential_helper: gnome-keyring }
    - { role: github-hub-user, set_git_alias: false, config_hub_protocol: https }
    - ansible-user
    - markdown-user
    - bats-user
    - hive-user
    - drake
    - drip
    - mongodb-tools-user
    - drive
