---
# Based on the following sources:
# https://ask.fedoraproject.org/en/question/55168/how-to-improve-fonts-and-font-rendering-in-fedora-20/
# http://worldofgnome.org/how-to-greatly-improve-font-rendering-under-fedora-20/
# http://peter.kingofcoders.com/?p=177

- yum: name=freetype-freeworld

- lineinfile:
    dest: /usr/share/glib-2.0/schemas/org.gnome.settings-daemon.plugins.xsettings.gschema.override
    create: yes
    line: '[org.gnome.settings-daemon.plugins.xsettings]'

- lineinfile:
    dest: /usr/share/glib-2.0/schemas/org.gnome.settings-daemon.plugins.xsettings.gschema.override
    regexp: '^hinting=\S+$'
    line: "hinting='{{ hinting }}'"
    state: '{{ "present" if hinting is defined else "absent" }}'
  notify:
    - compile glib schemas
    - print restart gnome session

- lineinfile:
    dest: /usr/share/glib-2.0/schemas/org.gnome.settings-daemon.plugins.xsettings.gschema.override
    regexp: '^antialiasing=\S+$'
    line: "antialiasing='{{ antialiasing }}'"
    state: '{{ "present" if antialiasing is defined else "absent" }}'
  notify:
    - compile glib schemas
    - print restart gnome session

- lineinfile:
    dest: /etc/X11/Xresources
    regexp: '^Xft.lcdfilter:\s+\S+$'
    line: 'Xft.lcdfilter: {{ lcdfilter }}'
    state: '{{ "present" if lcdfilter is defined else "absent" }}'
  notify:
    - print restart gnome session
