---

- package: name=ruby
  become: true

- package: name=hub
  become: true

- get_url: 
    url: 'https://raw.githubusercontent.com/github/hub/master/etc/hub.bash_completion.sh'
    dest: '/etc/bash_completion.d/'
  become: true
