---
- yum: name={{ item }}
  with_items:
    - gstreamer1-libav
    - gstreamer1-plugins-good
    - gstreamer1-plugins-ugly
    - gstreamer1-plugins-bad-free
    - gstreamer-ffmpeg
    - gstreamer-plugins-good
    - gstreamer-plugins-ugly
    - gstreamer-plugins-bad
    - gstreamer-plugins-bad-free
    - gstreamer-plugins-bad-nonfree
