- lineinfile:
    dest: /etc/hosts
    create: no
    line: "{{ item.line }}"
  with_items:
    - { line: '127.0.0.1\t\tsandbox.hortonworks.com' }
  sudo: yes

- lineinfile:
    dest: ~/.ssh/config
    create: yes
    line: "{{ item.line }}"
    mode: 0600
  with_items:
    - { line: 'NoHostAuthenticationForLocalhost yes' }

