- copy: src=google-chrome.repo dest=/etc/yum.repos.d/

- package: name=google-chrome-stable

- lineinfile:
    dest: /etc/xdg/mimeapps.list
    create: yes
    line: '[Default Applications]'

- lineinfile:
    dest: /etc/xdg/mimeapps.list
    create: yes
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: '{{ (set_default_browser | default(false)) | ternary("present", "absent") }}'
  with_items:
    - { regexp: '^text/html=', line: 'text/html=google-chrome.desktop' }
    - { regexp: '^application/xhtml\+xml=', line: 'application/xhtml+xml=google-chrome.desktop' }
    - { regexp: '^x-scheme-handler/http=', line: 'x-scheme-handler/http=google-chrome.desktop' }
    - { regexp: '^x-scheme-handler/https=', line: 'x-scheme-handler/https=google-chrome.desktop' }

- copy: src=master_preferences dest=/opt/google/chrome/

