---

- get_url: 
    url: 'https://releases.hashicorp.com/terraform/0.7.0/terraform_0.7.0_linux_amd64.zip'
    checksum: 'sha256:a196c63b967967343f3ae9bb18ce324a18b27690e2d105e1f38c5a2d7c02038d'
    dest: /tmp
  delegate_to: localhost

- file: path=/tmp/terraform_0.7.0_linux_amd64 state=directory
  delegate_to: localhost

- unarchive:
    src: /tmp/terraform_0.7.0_linux_amd64.zip
    dest: /tmp/terraform_0.7.0_linux_amd64
  delegate_to: localhost
  changed_when: false

- copy: src=/tmp/terraform_0.7.0_linux_amd64/ dest=/usr/local/bin

- file: path=/usr/local/bin/terraform mode=0755
