---

# http://unix.stackexchange.com/questions/69314/automated-ssh-keygen-without-passphrase-how
- name: Create ssh keypair with no passphrase
  shell: < /dev/zero ssh-keygen -q -N ""
  register: ssh_keygen
  changed_when: ssh_keygen.rc == 0
  failed_when: ssh_keygen.rc > 1

- name: Configure no host key checking for localhost
  lineinfile:
    dest: ~/.ssh/config
    create: yes
    line: '{{ item.line }}'
    mode: 0600
  with_items:
    - { line: 'NoHostAuthenticationForLocalhost yes' }

- name: Override SSH_ASKPASS if ssh_askpass defined
  lineinfile: 
    dest: ~/.bashrc
    regexp: '^export\s+SSH_ASKPASS=\S*$'
    line: 'export SSH_ASKPASS={{ ssh_askpass if ssh_askpass is defined }}'
    state: '{{ "present" if ssh_askpass is defined else "absent" }}'
