---

# http://unix.stackexchange.com/questions/69314/automated-ssh-keygen-without-passphrase-how
- name: Create ssh keypair with no passphrase
  shell: < /dev/zero ssh-keygen -q -N ""
  register: ssh_keygen
  changed_when: ssh_keygen.rc == 0
  failed_when: ssh_keygen.rc > 1

- name: Prepare ssh config for all hosts
  lineinfile:
    create: yes
    dest: ~/.ssh/config
    regexp: '\s*Host\s+\*\s*'
    line: 'Host *'
    insertbefore: BOF
    mode: 0600
  when: ssh_user.ssh_config_all_hosts is defined

- name: Apply ssh config for all hosts
  lineinfile:
    dest: ~/.ssh/config
    regexp: '\s*{{ item.keyword }}(\s+\S+)*'
    line: '    {{ item.keyword }} {{ item.arguments }}'
    insertafter: '\s*Host\s+\*'
  with_items: ssh_user.ssh_config_all_hosts | default([])

- name: Override SSH_ASKPASS if ssh_askpass defined
  lineinfile: 
    dest: ~/.bashrc
    regexp: '^export\s+SSH_ASKPASS=\S*$'
    line: 'export SSH_ASKPASS={{ ssh_user.ssh_askpass | default("") }}'
    state: '{{ "present" if ssh_user.ssh_askpass is defined else "absent" }}'
